export type Quote = { text: string; author: string }

export const GIVING_QUOTES: Quote[] = [
  { text: "We rise by lifting others.", author: "Robert Ingersoll" },
  { text: "No one has ever become poor by giving.", author: "Anne Frank" },
  { text: "You have not lived today until you have done something for someone who can never repay you.", author: "John Bunyan" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank" },
  { text: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { text: "We make a living by what we get. We make a life by what we give.", author: "Winston Churchill" },
  { text: "If you want happiness for a lifetime, help somebody.", author: "Chinese Proverb" },
  { text: "There is no exercise better for the heart than reaching down and lifting people up.", author: "John Holmes" },
  { text: "The purpose of human life is to serve, and to show compassion and the will to help others.", author: "Albert Schweitzer" },
  { text: "The greatest good you can do for another is not just share your riches, but reveal to him his own.", author: "Benjamin Disraeli" },
  { text: "A candle loses nothing by lighting another candle.", author: "James Keller" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "For it is in giving that we receive.", author: "Francis of Assisi" },
  { text: "We live in deeds, not years: in thoughts, not breaths: in feelings, not in figures on a dial.", author: "Philip James Bailey" },
  { text: "The smallest act of kindness is worth more than the grandest intention.", author: "Oscar Wilde" },
  { text: "As we work to create light for others, we naturally create light in our own lives.", author: "Mary Anne Radmacher" },
  { text: "To help a person is to help all humanity.", author: "Muhammad Ali" },
  { text: "If you can't feed a hundred people, then feed just one.", author: "Mother Teresa" },
  { text: "I have found that among its other benefits, giving liberates the soul of the giver.", author: "Maya Angelou" },
  { text: "No one is useless in this world who lightens the burdens of another.", author: "Charles Dickens" },
  { text: "The sole meaning of life is to serve humanity.", author: "Leo Tolstoy" },
  { text: "The best antidote I know for worry is work.", author: "George Bernard Shaw" },
  { text: "Do all the good you can, by all the means you can, in all the ways you can.", author: "John Wesley" },
  { text: "A good deed is never lost.", author: "Aesop" },
  { text: "One of the marvelous things about community is that it enables us to welcome and help people in a way that we couldn't as individuals.", author: "Jean Vanier" },
  { text: "The best thing to do with the best things in life is to give them away.", author: "Dorothy Day" },
  { text: "Everybody can be great, because everybody can serve.", author: "Martin Luther King Jr." },
  { text: "Life's most persistent and urgent question is, 'What are you doing for others?'", author: "Martin Luther King Jr." },
  { text: "If I cannot do great things, I can do small things in a great way.", author: "Martin Luther King Jr." },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Happiness doesn't result from what we get, but from what we give.", author: "Ben Carson" },
  { text: "Kindness begins with the understanding that we all struggle.", author: "Charles F. Glassman" },
  { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
  { text: "Kindness is free; sprinkle that stuff everywhere.", author: "Amy Leigh Mercree" },
  { text: "Carry out a random act of kindness, with no expectation of reward.", author: "Princess Diana" },
  { text: "A little thought and a little kindness are often worth more than a great deal of money.", author: "John Ruskin" },
  { text: "Kindness can become its own motive. We are made kind by being kind.", author: "Eric Hoffer" },
  { text: "Compassion is not a relationship between the healer and the wounded. It's a relationship between equals.", author: "Pema Chödrön" },
  { text: "If we have no peace, it is because we have forgotten that we belong to each other.", author: "Mother Teresa" },
  { text: "The best portion of a good man's life is his little, nameless, unremembered acts of kindness and of love.", author: "William Wordsworth" },
  { text: "Tenderness and kindness are not signs of weakness and despair, but manifestations of strength and resolution.", author: "Kahlil Gibran" },
  { text: "Kindness is the sunshine in which virtue grows.", author: "Robert Green Ingersoll" },
  { text: "Those who bring sunshine into the lives of others cannot keep it from themselves.", author: "James Matthew Barrie" },
  { text: "Give what you have. To someone, it may be better than you dare to think.", author: "Henry Wadsworth Longfellow" },
  { text: "You can give without loving, but you cannot love without giving.", author: "Amy Carmichael" },
  { text: "Generosity is giving more than you can, and pride is taking less than you need.", author: "Kahlil Gibran" },
  { text: "We cannot live only for ourselves. A thousand fibers connect us with our fellow men.", author: "Herman Melville" },
  { text: "The value of a man resides in what he gives and not in what he is capable of receiving.", author: "Albert Einstein" },
  { text: "What we have done for ourselves alone dies with us; what we have done for others and the world remains and is immortal.", author: "Albert Pike" },
  { text: "There is more happiness in giving than in receiving.", author: "Jesus Christ" },
  { text: "It is more blessed to give than to receive.", author: "Jesus Christ" },
  { text: "The greatest use of a life is to spend it for something that outlasts it.", author: "William James" },
  { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali" },
  { text: "The best way to cheer yourself is to try to cheer someone else up.", author: "Mark Twain" },
  { text: "We are here to add what we can to life, not to get what we can from life.", author: "William Osler" },
  { text: "The greatest gift you can give to others is the gift of unconditional love and acceptance.", author: "Brian Tracy" },
  { text: "A kind gesture can reach a wound that only compassion can heal.", author: "Steve Maraboli" },
  { text: "Helping people in need is a good and essential part of my life, a kind of destiny.", author: "Princess Diana" },
  { text: "If you become a helper of hearts, springs of wisdom will flow from your heart.", author: "Rumi" },
  { text: "What we do for ourselves is what we do for others.", author: "David Deida" },
  { text: "The happiest people are those who do the most for others.", author: "Booker T. Washington" },
  { text: "A generous person will prosper; whoever refreshes others will be refreshed.", author: "King Solomon" },
  { text: "Let us be kinder to one another.", author: "Aldous Huxley" },
  { text: "The best way to serve God is to serve man.", author: "Swami Vivekananda" },
  { text: "They are not poor that have little, but they that desire much.", author: "Thomas Fuller" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "We can do no great things, only small things with great love.", author: "Mother Teresa" },
  { text: "Never worry about numbers. Help one person at a time and always start with the person nearest you.", author: "Mother Teresa" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
  { text: "Love cannot remain by itself - it has no meaning. Love has to be put into action.", author: "Mother Teresa" },
  { text: "It's not how much we give but how much love we put into giving.", author: "Mother Teresa" },
  { text: "The miracle is this: the more we share, the more we have.", author: "Leonard Nimoy" },
  { text: "Giving is not just about making a donation. It is about making a difference.", author: "Kathy Calvin" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Only by giving are you able to receive more than you already have.", author: "Jim Rohn" },
  { text: "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.", author: "Desmond Tutu" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "Ubuntu: I am because we are.", author: "African Proverb" },
  { text: "A person is a person through other persons.", author: "Desmond Tutu" },
  { text: "We cannot help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { text: "The best way to serve humanity is to help others.", author: "Albert Schweitzer" },
  { text: "We should be too big to take offense and too noble to give it.", author: "Abraham Lincoln" },
  { text: "We must find time to stop and thank the people who make a difference in our lives.", author: "John F. Kennedy" },
  { text: "The greatest work that kindness does to others is that it makes them kind themselves.", author: "Amelia Earhart" },
  { text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
  { text: "In a world where you can be anything, be kind.", author: "Jennifer Dukes Lee" },
  { text: "Charity begins at home, but should not stay there.", author: "Charles Dickens" },
  { text: "No one is useless who makes another lighter.", author: "Charles Dickens" },
  { text: "The best way to find happiness is to help someone else find it.", author: "Dalai Lama" },
  { text: "A life not lived for others is not a life.", author: "Mother Teresa" },
  { text: "The best way to help yourself is to help others.", author: "Booker T. Washington" },
  { text: "We cannot do everything, but we can do something.", author: "Helen Keller" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "Life's most persistent and urgent question is, 'What are you doing for others?'", author: "Martin Luther King Jr." },
  { text: "The purpose of life is not to be happy. It is to be useful.", author: "Ralph Waldo Emerson" },
  { text: "To serve is beautiful, but only if it is done with joy and a whole heart.", author: "Pearl S. Buck" },
  { text: "The greatest gift is a portion of thyself.", author: "Ralph Waldo Emerson" },
]

export function getRandomQuote(): Quote {
  return GIVING_QUOTES[Math.floor(Math.random() * GIVING_QUOTES.length)]
}
